//Url's dos filmes

//FILMES

//DRAMA 
export let collateralBeauty = {"Title":"Collateral Beauty","Year":"2016","Rated":"PG-13","Released":"16 Dec 2016","Runtime":"97 min","Genre":"Drama, Romance","Director":"David Frankel","Writer":"Allan Loeb","Actors":"Will Smith, Edward Norton, Kate Winslet","Plot":"Retreating from life after a tragedy, a man questions the universe by writing to Love, Time, and Death. Receiving unexpected answers, he begins to see how these things interlock and how even loss can reveal moments of meaning and bea","Language":"English","Country":"United States","Awards":"1 win & 6 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMTQ5ODE4MTY2NV5BMl5BanBnXkFtZTgwMzM2NzEzMDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.8/10"},{"Source":"Rotten Tomatoes","Value":"13%"},{"Source":"Metacritic","Value":"23/100"}],"Metascore":"23","imdbRating":"6.8","imdbVotes":"95,356","imdbID":"tt4682786","Type":"movie","DVD":"14 Mar 2017","BoxOffice":"$31,016,021","Production":"Likely Story, Anonymous Content, PalmStar Media, Overbrook Entertainment","Website":"N/A","Response":"True"}

export let wiplash = {"Title":"Whiplash","Year":"2014","Rated":"R","Released":"15 Oct 2014","Runtime":"106 min","Genre":"Drama, Music","Director":"Damien Chazelle","Writer":"Damien Chazelle","Actors":"Miles Teller, J.K. Simmons, Melissa Benoist","Plot":"A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.","Language":"English","Country":"United States","Awards":"Won 3 Oscars. 97 wins & 145 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Metacritic","Value":"88/100"}],"Metascore":"88","imdbRating":"8.5","imdbVotes":"757,861","imdbID":"tt2582802","Type":"movie","DVD":"02 Dec 2014","BoxOffice":"$13,092,000","Production":"Blumhouse, Bold Films, Right of Way Films","Website":"N/A","Response":"True"}

export let moonlight = {"Title":"Moonlight","Year":"2016","Rated":"R","Released":"18 Nov 2016","Runtime":"111 min","Genre":"Drama","Director":"Barry Jenkins","Writer":"Barry Jenkins, Tarell Alvin McCraney","Actors":"Mahershala Ali, Naomie Harris, Trevante Rhodes","Plot":"A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.","Language":"English","Country":"United States","Awards":"Won 3 Oscars. 222 wins & 292 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Metacritic","Value":"99/100"}],"Metascore":"99","imdbRating":"7.4","imdbVotes":"286,871","imdbID":"tt4975722","Type":"movie","DVD":"28 Feb 2017","BoxOffice":"$27,854,932","Production":"Plan B Entertainment, Upload Films, Pastel","Website":"N/A","Response":"True"}

export let knivesOut = {"Title":"Knives Out","Year":"2019","Rated":"PG-13","Released":"27 Nov 2019","Runtime":"130 min","Genre":"Comedy, Crime, Drama","Director":"Rian Johnson","Writer":"Rian Johnson","Actors":"Daniel Craig, Chris Evans, Ana de Armas","Plot":"A detective investigates the death of a patriarch of an eccentric, combative family.","Language":"English, Spanish, Hindi","Country":"United States","Awards":"Nominated for 1 Oscar. 49 wins & 113 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"7.9","imdbVotes":"515,678","imdbID":"tt8946378","Type":"movie","DVD":"12 Jun 2020","BoxOffice":"$165,363,234","Production":"FilmNation Entertainment, Media Rights Capital","Website":"N/A","Response":"True"}

export let pijama = {"Title":"The Boy in the Striped Pyjamas","Year":"2008","Rated":"PG-13","Released":"26 Nov 2008","Runtime":"94 min","Genre":"Drama, History, War","Director":"Mark Herman","Writer":"John Boyne, Mark Herman","Actors":"Asa Butterfield, David Thewlis, Rupert Friend","Plot":"Through the innocent eyes of Bruno, the eight-year-old son of the commandant at a German concentration camp, a forbidden friendship with a Jewish boy on the other side of the camp fence has startling and unexpected consequences.","Language":"English","Country":"United Kingdom, United States","Awards":"7 wins & 7 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMTMzMTc3MjA5NF5BMl5BanBnXkFtZTcwOTk3MDE5MQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Metacritic","Value":"55/100"}],"Metascore":"55","imdbRating":"7.8","imdbVotes":"198,757","imdbID":"tt0914798","Type":"movie","DVD":"10 Mar 2009","BoxOffice":"$9,046,156","Production":"Heyday Films, Miramax Films","Website":"N/A","Response":"True"}

//ACAO/HEROI 🙏
export let theSuiceSquad = {"Title":"The Suicide Squad","Year":"2016","Rated":"N/A","Released":"16 Aug 2016","Runtime":"12 min","Genre":"Animation, Short, Action","Director":"Cohen Certenberg","Writer":"Cohen Certenberg","Actors":"Gabriel Johnson, Jackson Trent, Mason D. Sonnier","Plot":"When Lex Luthor's experimental elixir is put on the black market for terrorist practices, the Suicide Squad shows up to stop it.","Language":"English","Country":"United States","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMzMwMzkwNDYtMjBjZi00MjY2LWI1MjYtYmNjMzA1NDUyZTAyXkEyXkFqcGdeQXVyNjA5NTQ3MTc@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.5/10"}],"Metascore":"N/A","imdbRating":"6.5","imdbVotes":"9","imdbID":"tt6882516","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

export let ironMan = {"Title":"Iron Man","Year":"2010","Rated":"TV-14","Released":"23 Jul 2011","Runtime":"25 min","Genre":"Animation, Action, Sci-Fi","Director":"N/A","Writer":"N/A","Actors":"Adrian Pasdar, Ben Diskin, Eden Riegel","Plot":"When Tony Stark branches his company into Japan, he is opposed by the nefarious Zodiac organization. It's up to Stark's Iron Man to defeat the Zodiac, and defend Japan.","Language":"English, Japanese","Country":"United States, Japan","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMDFjZmEyZTAtMGRmOC00M2FlLTkyNTEtMjE1YzM3YTlhOTUwXkEyXkFqcGdeQXVyMjY4MzQzNDk@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.4/10"}],"Metascore":"N/A","imdbRating":"6.4","imdbVotes":"1,197","imdbID":"tt1707807","Type":"series","totalSeasons":"1","Response":"True"}

export let blackPanther = {"Title":"Black Panther","Year":"2018","Rated":"PG-13","Released":"16 Feb 2018","Runtime":"134 min","Genre":"Action, Adventure, Sci-Fi","Director":"Ryan Coogler","Writer":"Ryan Coogler, Joe Robert Cole, Stan Lee","Actors":"Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o","Plot":"T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.","Language":"English, Swahili, Nama, Xhosa, Korean","Country":"United States, South Africa","Awards":"Won 3 Oscars. 115 wins & 281 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"88/100"}],"Metascore":"88","imdbRating":"7.3","imdbVotes":"669,870","imdbID":"tt1825683","Type":"movie","DVD":"02 May 2018","BoxOffice":"$700,426,566","Production":"Walt Disney Pictures","Website":"N/A","Response":"True"}

export let aquaman = {"Title":"Aquaman","Year":"2018","Rated":"PG-13","Released":"21 Dec 2018","Runtime":"143 min","Genre":"Action, Adventure, Fantasy","Director":"James Wan","Writer":"David Leslie Johnson-McGoldrick, Will Beall, Geoff Johns","Actors":"Jason Momoa, Amber Heard, Willem Dafoe","Plot":"Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.","Language":"English, Russian, Maori, Italian","Country":"United States, Australia","Awards":"2 wins & 39 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.9/10"},{"Source":"Metacritic","Value":"55/100"}],"Metascore":"55","imdbRating":"6.9","imdbVotes":"410,730","imdbID":"tt1477834","Type":"movie","DVD":"26 Mar 2019","BoxOffice":"$335,061,807","Production":"Peter Safran","Website":"N/A","Response":"True"}

export let infinityWar = {"Title":"Avengers: Infinity War","Year":"2018","Rated":"PG-13","Released":"27 Apr 2018","Runtime":"149 min","Genre":"Action, Adventure, Sci-Fi","Director":"Anthony Russo, Joe Russo","Writer":"Christopher Markus, Stephen McFeely, Stan Lee","Actors":"Robert Downey Jr., Chris Hemsworth, Mark Ruffalo","Plot":"The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.","Language":"English","Country":"United States","Awards":"Nominated for 1 Oscar. 46 wins & 78 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Metacritic","Value":"68/100"}],"Metascore":"68","imdbRating":"8.4","imdbVotes":"912,997","imdbID":"tt4154756","Type":"movie","DVD":"14 Aug 2018","BoxOffice":"$678,815,482","Production":"Marvel Studios","Website":"N/A","Response":"True"}

export let manOfSteel = {"Title":"Man of Steel","Year":"2013","Rated":"PG-13","Released":"14 Jun 2013","Runtime":"143 min","Genre":"Action, Adventure, Sci-Fi","Director":"Zack Snyder","Writer":"David S. Goyer, Christopher Nolan, Jerry Siegel","Actors":"Henry Cavill, Amy Adams, Michael Shannon","Plot":"An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened, when other survivors of his home planet invade Earth.","Language":"English","Country":"United States, United Kingdom","Awards":"7 wins & 46 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTk5ODk1NDkxMF5BMl5BanBnXkFtZTcwNTA5OTY0OQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Metacritic","Value":"55/100"}],"Metascore":"55","imdbRating":"7.0","imdbVotes":"727,219","imdbID":"tt0770828","Type":"movie","DVD":"12 Nov 2013","BoxOffice":"$291,045,518","Production":"Syncopy, Warner Bros.","Website":"N/A","Response":"True"}


//ROMANCE 🙏
export let yourName = {"Title":"Your Name","Year":"2015","Rated":"N/A","Released":"04 Jul 2015","Runtime":"22 min","Genre":"Short","Director":"Megumi Shiraishi","Writer":"N/A","Actors":"N/A","Plot":"Ibe Riki and Riko Takeo are preparing for a wedding ceremony.","Language":"N/A","Country":"Japan","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMGY0ZjY4ZGItNmY1Ny00YzAwLWI0Y2EtODQwZTcwMDU0NzgyXkEyXkFqcGdeQXVyMTgwOTE5NDk@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"}],"Metascore":"N/A","imdbRating":"8.9","imdbVotes":"285","imdbID":"tt6033368","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

export let prideAndPrejudice = {"Title":"Pride and Prejudice","Year":"1995","Rated":"TV-PG","Released":"14 Jan 1996","Runtime":"327 min","Genre":"Drama, Romance","Director":"N/A","Writer":"N/A","Actors":"Colin Firth, Jennifer Ehle, Susannah Harker","Plot":"Pride And Prejudice","Language":"English","Country":"United Kingdom","Awards":"Won 1 Primetime Emmy. 9 wins & 13 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMDM0MjFlOGYtNTg2ZC00MmRkLTg5OTQtM2U5ZjUyYTgxZThiXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"}],"Metascore":"N/A","imdbRating":"8.8","imdbVotes":"78,928","imdbID":"tt0112130","Type":"series","totalSeasons":"1","Response":"True"}

export let aboutTime = {"Title":"About Time","Year":"2013","Rated":"R","Released":"08 Nov 2013","Runtime":"123 min","Genre":"Comedy, Drama, Fantasy","Director":"Richard Curtis","Writer":"Richard Curtis","Actors":"Domhnall Gleeson, Rachel McAdams, Bill Nighy","Plot":"At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out not to be as easy as you might think.","Language":"English","Country":"United Kingdom, United States","Awards":"3 wins & 9 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMTA1ODUzMDA3NzFeQTJeQWpwZ15BbWU3MDgxMTYxNTk@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Metacritic","Value":"55/100"}],"Metascore":"55","imdbRating":"7.8","imdbVotes":"320,420","imdbID":"tt2194499","Type":"movie","DVD":"04 Feb 2014","BoxOffice":"$15,322,921","Production":"Working Title Films","Website":"N/A","Response":"True"}

export let her = {"Title":"Her","Year":"2013","Rated":"R","Released":"10 Jan 2014","Runtime":"126 min","Genre":"Drama, Romance, Sci-Fi","Director":"Spike Jonze","Writer":"Spike Jonze","Actors":"Joaquin Phoenix, Amy Adams, Scarlett Johansson","Plot":"In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.","Language":"English","Country":"United States","Awards":"Won 1 Oscar. 83 wins & 186 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Metacritic","Value":"91/100"}],"Metascore":"91","imdbRating":"8.0","imdbVotes":"564,058","imdbID":"tt1798709","Type":"movie","DVD":"13 May 2014","BoxOffice":"$25,568,251","Production":"Annapurna Pictures","Website":"N/A","Response":"True"}

export let oneDay = {"Title":"One Day","Year":"2011","Rated":"PG-13","Released":"19 Aug 2011","Runtime":"107 min","Genre":"Drama, Romance","Director":"Lone Scherfig","Writer":"David Nicholls","Actors":"Anne Hathaway, Jim Sturgess, Patricia Clarkson","Plot":"After spending the night together on the night of their college graduation Dexter and Emma are shown each year on the same date to see where they are in their lives. They are sometimes together, sometimes not, on that day.","Language":"English","Country":"United States, United Kingdom","Awards":"1 win & 2 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMTQ3NTg2MDI3NF5BMl5BanBnXkFtZTcwMjc5MTA1NA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Metacritic","Value":"48/100"}],"Metascore":"48","imdbRating":"7.0","imdbVotes":"144,604","imdbID":"tt1563738","Type":"movie","DVD":"29 Nov 2011","BoxOffice":"$13,843,771","Production":"Color Force","Website":"N/A","Response":"True"}

//TERROR🙏

export let hereditary = {"Title":"Hereditary","Year":"2018","Rated":"R","Released":"08 Jun 2018","Runtime":"127 min","Genre":"Drama, Horror, Mystery","Director":"Ari Aster","Writer":"Ari Aster","Actors":"Toni Collette, Milly Shapiro, Gabriel Byrne","Plot":"A grieving family is haunted by tragic and disturbing occurrences.","Language":"English, Spanish","Country":"United States","Awards":"46 wins & 109 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Metacritic","Value":"87/100"}],"Metascore":"87","imdbRating":"7.3","imdbVotes":"263,704","imdbID":"tt7784604","Type":"movie","DVD":"04 Sep 2018","BoxOffice":"$44,069,456","Production":"PalmStar Media","Website":"N/A","Response":"True"}

export let insidious = {"Title":"Insidious","Year":"2010","Rated":"PG-13","Released":"01 Apr 2011","Runtime":"103 min","Genre":"Horror, Mystery, Thriller","Director":"James Wan","Writer":"Leigh Whannell","Actors":"Patrick Wilson, Rose Byrne, Ty Simpkins","Plot":"A family looks to prevent evil spirits from trapping their comatose child in a realm called The Further.","Language":"English","Country":"United States, Canada","Awards":"8 wins & 15 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMTYyOTAxMDA0OF5BMl5BanBnXkFtZTcwNzgwNTc1NA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.8/10"},{"Source":"Metacritic","Value":"52/100"}],"Metascore":"52","imdbRating":"6.8","imdbVotes":"289,806","imdbID":"tt1591095","Type":"movie","DVD":"12 Jul 2011","BoxOffice":"$54,009,150","Production":"Alliance, IM Global","Website":"N/A","Response":"True"}

export let us = {"Title":"Us","Year":"2019","Rated":"R","Released":"22 Mar 2019","Runtime":"116 min","Genre":"Horror, Mystery, Thriller","Director":"Jordan Peele","Writer":"Jordan Peele","Actors":"Lupita Nyong'o, Winston Duke, Elisabeth Moss","Plot":"A family's serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.","Language":"English","Country":"United States, China, Japan","Awards":"83 wins & 126 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BZTliNWJhM2YtNDc1MC00YTk1LWE2MGYtZmE4M2Y5ODdlNzQzXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.8/10"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"6.8","imdbVotes":"251,882","imdbID":"tt6857112","Type":"movie","DVD":"04 Jun 2019","BoxOffice":"$175,084,580","Production":"Monkeypaw Productions","Website":"N/A","Response":"True"}

export let run = {"Title":"Run","Year":"2020","Rated":"PG-13","Released":"20 Nov 2020","Runtime":"90 min","Genre":"Mystery, Thriller","Director":"Aneesh Chaganty","Writer":"Aneesh Chaganty, Sev Ohanian","Actors":"Sarah Paulson, Kiera Allen, Sara Sohn","Plot":"A homeschooled teenager begins to suspect her mother is keeping a dark secret from her.","Language":"English","Country":"United States, Canada","Awards":"3 wins & 4 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BZjdmZDlkMzItNTg0OS00MjAxLWE0ZTQtZjdhOWM1MTJkOTc0XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.7/10"},{"Source":"Metacritic","Value":"67/100"}],"Metascore":"67","imdbRating":"6.7","imdbVotes":"58,115","imdbID":"tt8633478","Type":"movie","DVD":"20 Nov 2020","BoxOffice":"N/A","Production":"Lionsgate","Website":"N/A","Response":"True"}

export let theBlairWitchProject = {"Title":"The Blair Witch Project","Year":"1999","Rated":"R","Released":"30 Jul 1999","Runtime":"81 min","Genre":"Horror, Mystery","Director":"Daniel Myrick, Eduardo Sánchez","Writer":"Daniel Myrick, Eduardo Sánchez, Heather Donahue","Actors":"Heather Donahue, Michael C. Williams, Joshua Leonard","Plot":"Three film students vanish after traveling into a Maryland forest to film a documentary on the local Blair Witch legend, leaving only their footage behind.","Language":"English","Country":"United States","Awards":"19 wins & 26 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BNzQ1NDBlNDItMDAyYS00YTI2LTgwMmYtMzAwMzg4NDFlM2ZmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.5/10"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"6.5","imdbVotes":"242,188","imdbID":"tt0185937","Type":"movie","DVD":"12 Sep 2010","BoxOffice":"$140,539,099","Production":"Haxan Films","Website":"N/A","Response":"True"}

//SERIES e ANIMES

export let naruto = {"Title":"Naruto","Year":"2002–2007","Rated":"TV-PG","Released":"10 Sep 2005","Runtime":"24 min","Genre":"Animation, Action, Adventure","Director":"N/A","Writer":"Masashi Kishimoto","Actors":"Junko Takeuchi, Maile Flanagan, Kate Higgins","Plot":"Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.","Language":"English, Japanese","Country":"Japan","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"}],"Metascore":"N/A","imdbRating":"8.3","imdbVotes":"82,124","imdbID":"tt0409591","Type":"series","totalSeasons":"1","Response":"True"}

export let theWitcher = {"Title":"The Witcher","Year":"2019–","Rated":"TV-MA","Released":"20 Dec 2019","Runtime":"60 min","Genre":"Action, Adventure, Fantasy","Director":"Tomek Baginski","Writer":"Lauren Schmidt","Actors":"Henry Cavill, Anna Shaffer, Freya Allan","Plot":"Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.","Language":"English","Country":"Poland, United States, Hungary","Awards":"9 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BOGE4MmVjMDgtMzIzYy00NjEwLWJlODMtMDI1MGY2ZDlhMzE2XkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"}],"Metascore":"N/A","imdbRating":"8.2","imdbVotes":"341,015","imdbID":"tt5180504","Type":"series","totalSeasons":"2","Response":"True"}

export let laCasaDePapel = {"Title":"La casa de papel","Year":"2017–2021","Rated":"TV-MA","Released":"02 May 2017","Runtime":"70 min","Genre":"Action, Crime, Mystery","Director":"N/A","Writer":"Álex Pina","Actors":"Úrsula Corberó, Álvaro Morte, Itziar Ituño","Plot":"An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.","Language":"Spanish, Russian, Serbian, English","Country":"Spain","Awards":"29 wins & 35 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BNDJkYzY3MzMtMGFhYi00MmQ4LWJkNTgtZGNiZWZmMTMxNzdlXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"}],"Metascore":"N/A","imdbRating":"8.3","imdbVotes":"372,460","imdbID":"tt6468322","Type":"series","totalSeasons":"5","Response":"True"}

export let gameOfThrones = {"Title":"Game of Thrones","Year":"2011–2019","Rated":"TV-MA","Released":"17 Apr 2011","Runtime":"57 min","Genre":"Action, Adventure, Drama","Director":"N/A","Writer":"David Benioff, D.B. Weiss","Actors":"Emilia Clarke, Peter Dinklage, Kit Harington","Plot":"Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.","Language":"English","Country":"United States, United Kingdom","Awards":"Won 59 Primetime Emmys. 382 wins & 626 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.2/10"}],"Metascore":"N/A","imdbRating":"9.2","imdbVotes":"1,867,688","imdbID":"tt0944947","Type":"series","totalSeasons":"8","Response":"True"}

export let bridgerton = {"Title":"Bridgerton","Year":"2020–","Rated":"TV-MA","Released":"25 Dec 2020","Runtime":"60 min","Genre":"Drama, Romance","Director":"N/A","Writer":"Chris Van Dusen","Actors":"Phoebe Dynevor, Regé-Jean Page, Nicola Coughlan","Plot":"Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.","Language":"English","Country":"United States","Awards":"Nominated for 12 Primetime Emmys. 6 wins & 41 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BYjIxMzZhMTMtNDQ1Mi00OTMwLTk2M2ItYzA0YmNjNDFlOTdhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"}],"Metascore":"N/A","imdbRating":"7.3","imdbVotes":"85,832","imdbID":"tt8740790","Type":"series","totalSeasons":"2","Response":"True"}